# These are supported funding model platforms

custom: ['https://www.buymeacoffee.com/vitim']
github: # Replace with up to 4 GitHub Sponsors-enabled victornpbs e.g., [user1, user2]
patreon: # Replace with a single Patreon victornpb
open_collective: # Replace with a single Open Collective victornpb
ko_fi: victornpb
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay victornpb
issuehunt: # Replace with a single IssueHunt victornpb
otechie: # Replace with a single Otechie victornpb
